# Generated by Django 4.1.7 on 2023-03-14 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps_ref_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'eps_ref_cita',
            },
        ),
        migrations.CreateModel(
            name='Especialidad_ref_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'especialidad_ref_cita',
            },
        ),
        migrations.CreateModel(
            name='Estado_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esalud', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'estado_cita',
            },
        ),
        migrations.CreateModel(
            name='Regimen_eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'regimen_eps_cita',
            },
        ),
        migrations.CreateModel(
            name='Tipo_servicio_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_servicio_cita',
            },
        ),
        migrations.CreateModel(
            name='Solicitud_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_s', models.DateTimeField()),
                ('fecha_cita', models.CharField(blank=True, max_length=200, null=True)),
                ('no_aut', models.CharField(blank=True, max_length=100, null=True)),
                ('atendido', models.BooleanField(default=False)),
                ('descartar', models.BooleanField(default=False)),
                ('l_espera', models.BooleanField(blank=True, default=False, null=True)),
                ('bloqueo_atencion', models.BooleanField(blank=True, default=False, null=True)),
                ('orden_img', models.ImageField(upload_to='data_pcte/orden')),
                ('aut_img', models.ImageField(upload_to='data_pcte/aut')),
                ('observacion_des', models.TextField(blank=True, null=True)),
                ('observacion_eps', models.TextField(blank=True, null=True)),
                ('fecha_aten', models.DateTimeField(blank=True, default=None, null=True)),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citas_medicas.eps_ref_cita')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citas_medicas.especialidad_ref_cita')),
                ('pcte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.paciente')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citas_medicas.regimen_eps')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citas_medicas.tipo_servicio_cita')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_tramite')),
                ('usuario_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud_cita',
            },
        ),
        migrations.CreateModel(
            name='Notificacion_msg_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_cita', models.CharField(max_length=20)),
                ('whatsapp', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('mail', models.BooleanField(default=False)),
                ('observacion', models.TextField()),
                ('id_aten', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas_medicas.solicitud_cita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion_envio_msg_cita',
            },
        ),
        migrations.CreateModel(
            name='Listado_espera_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('envio_msg', models.BooleanField(default=False)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas_medicas.solicitud_cita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listado_espera_cita',
            },
        ),
        migrations.CreateModel(
            name='Directorio_contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usr', models.CharField(blank=True, max_length=20, null=True)),
                ('no_id', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=280)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(max_length=100)),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_id')),
            ],
            options={
                'db_table': 'directorio_contactos_cita',
            },
        ),
    ]
