# Generated by Django 4.1.7 on 2023-03-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'departamento_sistema',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('razon_social', models.CharField(max_length=180)),
                ('nit', models.CharField(max_length=80)),
                ('dir', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('web', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('n_app', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'empresa_sistema',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=60)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.departamento')),
            ],
            options={
                'db_table': 'municipio_sistema',
            },
        ),
        migrations.CreateModel(
            name='Settings_msg_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('dir', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dir_server', models.CharField(max_length=100)),
                ('port_server', models.CharField(max_length=5)),
                ('usage', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'settings_msg_email_sistema',
            },
        ),
        migrations.CreateModel(
            name='Settings_msg_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_goip_linea', models.CharField(default='', max_length=5)),
                ('linea_goip_ip', models.CharField(default='', max_length=20)),
                ('linea_goip_user', models.CharField(default='', max_length=10)),
                ('linea_goip_password', models.CharField(default='', max_length=30)),
                ('linea_goip', models.BooleanField(default=False)),
                ('linea_issabel_nomb', models.CharField(default='', max_length=10)),
                ('linea_issabel_ip', models.CharField(default='', max_length=30)),
                ('linea_issabel_user', models.CharField(default='', max_length=10)),
                ('linea_issabel_password', models.CharField(default='', max_length=20)),
                ('linea_issabel', models.BooleanField(default=False)),
                ('usage', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'settings_msg_sms_sistema',
            },
        ),
        migrations.CreateModel(
            name='Settings_msg_whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(default='', max_length=30)),
                ('port', models.CharField(default='', max_length=7)),
                ('whatsapp', models.BooleanField(default=False)),
                ('usage', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'settings_msg_whatsapp_sistema',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sexo_sistema',
            },
        ),
        migrations.CreateModel(
            name='Tipo_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.CharField(max_length=3)),
                ('detalle', models.CharField(max_length=180)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_id_sistema',
            },
        ),
        migrations.CreateModel(
            name='Tipo_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('txt', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'tipo_tramite_sistema',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_id', models.CharField(max_length=20)),
                ('p_nombre', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('s_nombre', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('p_apellido', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('s_apellido', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('f_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion_residencia', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('telefono_fijo', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('telefono_movil', models.CharField(max_length=12)),
                ('grupo_s', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('envio_inf', models.BooleanField(default=True)),
                ('envio_publ', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, default='', null=True)),
                ('municipio_residencia', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.municipio')),
                ('sexo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.sexo')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_id')),
            ],
            options={
                'db_table': 'paciente_sistema',
            },
        ),
        migrations.CreateModel(
            name='Msg_whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('saludo', models.CharField(default='', max_length=180)),
                ('mensaje', models.TextField(default='')),
                ('detalle', models.TextField(default='')),
                ('observacion', models.TextField(default='')),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_tramite')),
            ],
            options={
                'db_table': 'msg_whatsapp_sistema',
            },
        ),
        migrations.CreateModel(
            name='Msg_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(default='')),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_tramite')),
            ],
            options={
                'db_table': 'msg_sms_sistema',
            },
        ),
        migrations.CreateModel(
            name='Msg_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('mensaje', models.TextField(default='')),
                ('detalle', models.TextField(default='')),
                ('recomendacion', models.TextField(default='')),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_tramite')),
            ],
            options={
                'db_table': 'msg_email_sistema',
            },
        ),
        migrations.CreateModel(
            name='Lista_negra_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_pcte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.paciente')),
            ],
            options={
                'db_table': 'lista_negra_msg_sistema',
            },
        ),
    ]
