# Generated by Django 4.1.7 on 2023-03-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'area_personal',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'cargo_personal',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'dependencia_personal',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_exp', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/photo')),
                ('activo', models.BooleanField(default=True)),
                ('acudiente', models.CharField(blank=True, max_length=90, null=True)),
                ('tel_acudiente', models.CharField(blank=True, max_length=12, null=True)),
                ('eps', models.CharField(blank=True, max_length=30, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal.area')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal.cargo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.paciente')),
            ],
            options={
                'db_table': 'registro_personal',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.dependencia'),
        ),
    ]
