# Generated by Django 4.1.7 on 2023-03-14 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultorio', models.CharField(max_length=30)),
                ('piso', models.CharField(max_length=2)),
                ('habilitado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultorio_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
                ('turno', models.CharField(blank=True, max_length=10, null=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modulo_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('tema', models.TextField()),
                ('order', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'publicidad_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(blank=True, max_length=1, null=True)),
                ('servicio', models.CharField(max_length=60)),
                ('rango_ini', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('horario', models.CharField(blank=True, max_length=250, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('habilitado', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'servicio_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_pcte', models.BooleanField(default=False)),
                ('tel', models.BooleanField(default=False)),
                ('letra', models.BooleanField(default=False)),
                ('impresion', models.BooleanField(default=False)),
                ('repr_audio_turno', models.BooleanField(default=False)),
                ('repr_audio_consult', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'settings_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turno_digital.servicio')),
            ],
            options={
                'db_table': 'turno_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Registro_digiturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_turno', models.IntegerField()),
                ('no_id', models.CharField(max_length=20)),
                ('tel', models.CharField(blank=True, max_length=14, null=True)),
                ('llamado', models.BooleanField(default=False)),
                ('r_llamado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('fecha_atendido', models.DateTimeField(blank=True, null=True)),
                ('aviso', models.BooleanField(default=False)),
                ('general', models.BooleanField(default=False)),
                ('preferencial', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='turno_digital.modulo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turno_digital.servicio')),
                ('tp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.tipo_id')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turno_pcte_digiturno',
            },
        ),
        migrations.CreateModel(
            name='Reg_consul_digiturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llamado', models.BooleanField(default=False)),
                ('u_llamado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('aviso', models.BooleanField(default=False)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turno_digital.consultorio')),
                ('id_pcte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.paciente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llamado_pcte_consultorio_digiturno',
            },
        ),
    ]
